### ISSUE TITLE
Submission1 checklist

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/squareone#16]
## Writing

- [x] cover letter
- [x] M feedback
- [x] how do we feel about the title
- [x] cross-check refs

## Code

- [x] revisit tests and double-check
- [x] high-level reproduction doc (this is much simpler than scads)
- [x] Figure formatting

## Periphera

- [x] data re-use/prior publication statements
- [x] iacuc - do we need a protocol number or something
- [x] grant numbers for LTREB/SKME support
- [x] post on bioRxiv
- [x] zenodo archives for soar and squareone (or wait until acceptance?)
