### ISSUE TITLE
Ecology checklist

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/squareone#17]
- [x] Cover letter
- [x] Author list
- [x] Original submission: Provide information describing the extent to which data or text in the manuscript have been used in other works that are published, in press, submitted, or soon to be submitted elsewhere. Enter this information in section “Dual Publication”.
- [x] No prior publication: Preprint OK if link is provided.
     - [x] Link to bioRxiv
- [x] Animal welfare: "Authors using experimental vertebrate animals must certify that their care was in accordance with institutional guidelines."
    - [x] IACUC protocol number
- [x]  Open research policy 
    - [x] Zenodo release (do this prior to submitting; can update through review)
- [x] Everything must be doublespaced in 12-pt Times New Roman
- [x] Abstract and intro begin on new pages
- [x] Tables and figures 1/page
- [x] Separate section for captions
- [x] 1 inch margins
- [x] Reports max 20pages, abstract max 200 words
